<?xml version="1.0"?>
<robot name="elektron" xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
	xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
	xmlns:xacro="http://ros.org/wiki/fixme"
	xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">
	<property name="M_PI" value="3.14159"/>

	<property name="base_size_x" value="0.38" />
	<property name="base_size_y" value="0.28" />
	<property name="base_size_z" value="0.18" />

	<property name="wheel_radius" value="0.05" />
	<property name="wheel_length" value="0.02" />
	<property name="caster_wheel_offset_y" value="0.1675" />

	<!-- ROBOT BASE DEFINITION -->
	<link name="base_link">
		<inertial>
			<mass value="15" />
			<origin xyz="-0.0 0 ${base_size_z/2}" />
			<inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
		</inertial>

		<visual>
			<origin xyz="-0.0 0 0.115" rpy="0 0 0" />
			<geometry>
				<!--<box size="0.38 0.28 0.20" />-->
				<mesh filename="package://elektron_description/meshes/elektron_body.dae"/>
			</geometry>
		</visual>

		<collision>
			<origin xyz="-0.0 0 0.115" rpy="0 0 0" />
			<geometry>
				<box size="0.30 0.28 0.20" />
			</geometry>

			<material name="Cyan">
				<color rgba="0 255 255 1.0"/>
			</material>

		</collision>
	</link>
	<!-- WHEELS MACRO -->
	<xacro:macro name="erratic_wheel" params="suffix parent reflect offset m">
		
			<joint name="${parent}_${suffix}_wheel_joint" type="continuous">
				<origin xyz="${offset} ${reflect*caster_wheel_offset_y} ${wheel_radius}" rpy="0	0 0"/>
				<axis xyz="0 1 0" />
				<anchor xyz="0 0 0" />
				<limit effort="100" velocity="100" />
				<joint_properties damping="0.0" friction="0.0" />
				<parent link="${parent}" />
				<child link="${parent}_${suffix}_wheel_link" />
	 			<dynamics damping="0.0" friction="0.0"/>
			</joint>

			<link name="${parent}_${suffix}_wheel_link">
				<inertial>
					<mass value="0.1" />
					<!-- check jmh 20081205 -->
					<origin xyz=" 0 0 0 " />
					<inertia ixx="0.012411765597" ixy="0.0" ixz="0.0" iyy="0.015218160428" iyz="0.0" izz="0.011763977943"/>
				</inertial>
				<visual>
					<origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
					<geometry>
						<cylinder radius="${wheel_radius}" length="${wheel_length}" />
					</geometry>

				</visual>
				<collision>
					<origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
					<geometry>
						<cylinder radius="${wheel_radius}" length="${wheel_length}" />
					</geometry>
				</collision>
			</link>
			<!-- WHEELS FRICTION PARAMS -->
			<gazebo reference="${parent}_${suffix}_wheel_link">
			      <mu1 value="${m}" />
			      <mu2 value="${m}" />
			      <kp value="100000.0" />
			      <kd value="0.00001" />
			      <maxVel value="1.0" />
			      <minDepth value="0.0001" />
			</gazebo>    

	</xacro:macro>

	<!-- WHEELS DEFINITION -->
	<xacro:erratic_wheel suffix="left" parent="base_link" reflect="1" offset="0" m="0.900"/>
	<xacro:erratic_wheel suffix="left_front" parent="base_link" reflect="1" offset="0.15" m="0"/>
	<xacro:erratic_wheel suffix="left_rear" parent="base_link" reflect="1" offset="-0.15" m="0"/>

	<xacro:erratic_wheel suffix="right" parent="base_link" reflect="-1" offset="0" m="0.900"/>
	<xacro:erratic_wheel suffix="right_front" parent="base_link" reflect="-1" offset="0.15"
		m="0"/>
	<xacro:erratic_wheel suffix="right_rear" parent="base_link" reflect="-1" offset="-0.15"	m="0"/>


	<!-- INCLUDE SICK LMX100 LASER -->
	<!-- <include filename="$(find elektron_description)/urdf/sensors/sick_laser_lmx_100.urdf" />-->
	
	<!-- INCLUDE KINECT -->
	<include filename="$(find elektron_description)/urdf/sensors/kinect.urdf.xacro"/>
	<sensor_kinect  parent="base_link"/>

	<!-- add differentional drive to wheels -->
	<gazebo>
		<plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
			<alwaysOn>true</alwaysOn>
			<updateRate>100</updateRate>
			<leftJoint>base_link_left_wheel_joint</leftJoint>
			<rightJoint>base_link_right_wheel_joint</rightJoint>
			<wheelSeparation>${caster_wheel_offset_y*2}</wheelSeparation>
			<wheelDiameter>${wheel_radius*2}</wheelDiameter>
			<torque>5</torque>
			<commandTopic>cmd_vel</commandTopic>
			<odometryTopic>odom</odometryTopic>
			<odometryFrame>odom</odometryFrame>
			<robotBaseFrame>base_link</robotBaseFrame>
		</plugin>
	</gazebo>

		


	<!-- SET gazebo-ROS CONTROL -->
	<gazebo>
	  	<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
	    	<robotNamespace>/elektron</robotNamespace>
	  	</plugin>
	</gazebo>
	<!-- ADD position CONTROLLER - left wheel -->
	<transmission name="tran_effort_left_wheel_joint">
		<type>effort_controllers/JointPositionController</type>
		<joint name="base_link_left_wheel_joint">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="motor_base_link_left_wheel_joint">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>
	<!-- ADD position CONTROLLER - right wheel -->
	<transmission name="tran_effort_right_wheel_joint">
		<type>effort_controllers/JointPositionController</type>
		<joint name="base_link_right_wheel_joint">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="motor_base_link_right_wheel_joint">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
      			<mechanicalReduction>1</mechanicalReduction>
    		</actuator>
  	</transmission>
	<!-- ADD velocity CONTROLLER - left wheel -->
  	<transmission name="tran_vel_left_wheel_joint">
    		<type>effort_controllers/JointVelocityController</type>
    		<joint name="base_link_left_wheel_joint">
      			<hardwareInterface>VelocityJointInterface</hardwareInterface>
    		</joint>
    		<actuator name="motor_base_link_left_wheel_joint">
      			<hardwareInterface>VelocityJointInterface</hardwareInterface>
    		</actuator>
  	</transmission>
	<!-- ADD velocity CONTROLLER - right wheel -->
	<transmission name="tran_vel_right_wheel_joint">
		<type>effort_controllers/JointVelocityController</type>
		<joint name="base_link_right_wheel_joint">
     			<hardwareInterface>VelocityJointInterface</hardwareInterface>
    		</joint>
    		<actuator name="motor_base_link_right_wheel_joint">
      			<hardwareInterface>VelocityJointInterface</hardwareInterface>
    		</actuator>
  	</transmission>

</robot>
